# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='pic_path',
            new_name='pic',
        ),
    ]
