# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0002_essay_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='name',
        ),
    ]
