# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_remove_essay_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='area',
            field=models.IntegerField(),
        ),
    ]
