# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20170707_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='pic_path',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
