# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0006_essay_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
